# Generated by Django 2.0 on 2018-06-04 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wy_diamonds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rmb_change_info',
            name='changed_money',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rmb_change_info',
            name='last_mondey',
            field=models.IntegerField(default=0),
        ),
    ]
